### ISSUE TITLE
Anfang

### ISSUE THREAD

**Issue by gast-dan** [gast-dan/Gruppenarbeit_wiss_arbeiten#1]
Ich poste um zu testen, ob man emailbenachrichtigungrn für solche posts kriegt.

Wir könnten auch schonmal mit dem ersten Teil anfangen (also das Dataset erstellen)
Ich würde mich freiwillig dafür melden, bräuchte dann noch eine weitere Person

Gruß,
Daniel

**Comment by JonaMessling** [comment]
Hi, ja ich würde auch am ersten Teil der Aufgabe mitarbeiten

**Comment by gast-dan** [comment]
Alles klar, dann schließe ich das Issue hier.
