### ISSUE TITLE
.csv Datei für Dataset

### ISSUE THREAD

**Issue by liianaa** [gast-dan/Gruppenarbeit_wiss_arbeiten#11]
@gast-dan @JonaMessling für die Analyse des Datensatzes brauchen wir noch eine .csv Datei, da wir den Skript nicht angucken sollten, könntet ihr das noch in Repository dazupacken? :)

**Comment by JonaMessling** [comment]
Hi, habe einen Datensatz erzeugt und hinzugefügt :) @liianaa @GoFisch

**Comment by GoFisch** [comment]
Ok danke :)
