### ISSUE TITLE
Problem bei der Funktion ordinal_kategorie (e)

### ISSUE THREAD

**Issue by liianaa** [gast-dan/Gruppenarbeit_wiss_arbeiten#13]
Ich hab gerade festgestellt, dass die Funktion ordinal_kategorie funktioniert bei uns nicht ganz richtig, da der Median anstatt mittel als hoch kategorisiert wird. Also z.B wenn wir 3 Elementen in einem Vektor haben, wird es niedrig hoch hoch kategoriesiert und nich niedrig mittel hoch.

**Comment by gast-dan** [comment]
Ich habe den Funktion in helper.R etwas abgewandelt. Kannst du mal versuchen ob es jetzt besser geht?

**Comment by liianaa** [comment]
Jetzt funktioniert die Funktion bei Vektoren mit einer ungeraden Anzahl von Elementen ganz gut, aber z.B bei der Vektor 1,2,3,4 wird niedrig mittel hoch hoch ausgegeben, ich würde auch 3 als mittel betrachten

**Comment by liianaa** [comment]
Ich habe die Funktion ein bisschen verändert, jetzt funktionert es glaub ich besser :)

**Comment by gast-dan** [comment]
Ja sieht besser aus ^^
