### ISSUE TITLE
Abhängikeiten Datensatz

### ISSUE THREAD

**Issue by JonaMessling** [gast-dan/Gruppenarbeit_wiss_arbeiten#2]
Ich habe die Abhängikeiten der Parameter relativ umständlich eingebaut, kannst vielleicht mal drüber schauen, ob dir was besseres einfällt. R hat ja auch immer Lösungen ohne Schleifen, die fallen mir nur meistens nicht ein^^. @gast-dan

**Comment by gast-dan** [comment]
Finde ich gar nicht so umständlich und die Ideen sind gut, die du umgesetzt hast. Und gerade bei so einem kurzen Skript ist die Laufzeit eh nicht so wichtig, da ist es besser wenn es einfacher lesbar/verständlich ist ^^

Ich hätte noch die Idee, dass wir versuchen da irgendeinen "deutlicheren" Zusammenhang reinzubauen, also etwas was die anderen später auch relativ einfach herauskriegen können, muss ja nicht alles zu komplex sein xD
Man könnte vielleicht am Ende auf interesse_mathe nochmal +2 oder +3 rechnen, falls Mathe_LK 1 ist (und dann gegebenenfalls auf 7 setzen, falls es darüber ist). Das müsste man dann ziemlich deutlich sehen, wenn man sich Einträge mit Mathe_LK = 1 und  = 0 getrennt ansieht. Was meinst du? @JonaMessling

**Comment by JonaMessling** [comment]
Wird der Zusammenhang dann nicht "zu" deutlich? Der dann dann ja quasi in beide Richtungen. @gast-dan

**Comment by gast-dan** [comment]
Ja vielleicht springt das dann so ins Auge, dass die anderen Zusammenhänge untergehen ^^"

Ich würde sagen wir lassen das hier erstmal so und fangen mit dem zweiten Teil der Aufgabe an. Wenn wir da schon ein bisschen was haben können wir beiden ja schonmal austesten, ob man das was wir gemacht haben überhaupt herausanalysiert bekommt. @JonaMessling

**Comment by JonaMessling** [comment]
Okay hört sich gut an. Wollen wir für den zweiten Teil die Funktionen erstmal auf alle 4 Leute aufteilen? Dann kann jeder zumindest einen Ansatz machen und evtl. können wir uns dann gegenseitig korrigieren?

**Comment by gast-dan** [comment]
Klingt gut, jeder macht dann schonmal nen Anfang für 1-2 und wir können dann ja ein Issue pro Funktion aufmachen mit Anmerkungen (oder Fragen, falls man selbst nicht weiterkommt)

Kannst du für deinen branch hier ein Pull Request machen?
Ich glaube es ist besser, wenn wir das hier schonmal in den main branch integrieren, bevor noch mehr geändert wird @JonaMessling
